### ISSUE TITLE
Duplicate module name: Sample

### ISSUE THREAD

**Issue by antoine-souesme** [99xt/first-born#4] opened 2019-04-02 07:22 UTC
**Describe the bug**
```
(node:3022) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: Sample
  Paths: /Users/antoinesouesme/Documents/tests/rn-first-born/node_modules/@99xt/first-born/node_modules/react-native/Libraries/Sample/package.json collides with /Users/antoinesouesme/Documents/tests/rn-first-born/node_modules/react-native/Libraries/Sample/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/Users/antoinesouesme/Documents/tests/rn-first-born/node_modules/jest-haste-map/build/index.js:462:17)
    at workerReply (/Users/antoinesouesme/Documents/tests/rn-first-born/node_modules/jest-haste-map/build/index.js:512:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3022) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3022) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**

1. `expo init rn-first-born`
2. `yarn add -D create-react-class react-native-vector-icons`
3. `yarn add @99xt/first-born`

Node v10.15.3
Yarn v1.13.0
macOS 10.14.4

**Expected behavior**
Application is running.

**Smartphone (please complete the following information):**
 - Device: iPhone Xs
 - OS: 12.2
 - Expo client

**Comment by samsam-026** [comment] 2019-04-02 09:46
Hi @antoine-souesme-needone,
Currently working on fixing that.
As a temporary fix, just delete the node_modules folder generated inside first-born
Delete the folder `rn-first-born/node_modules/@99xt/first-born/node_modules`
It will work fine after that. 
Will close this issue when completely fixed

**Comment by antoine-souesme** [comment] 2019-04-02 09:59
It works! Thank you for that temporary fix.

**Comment by cohawk** [comment] 2019-04-02 12:55
Downgrading your deps to `"react-native": "0.57.8"` & `"react": "16.6.3",` will also resolve the haste-map naming collision.


Also quick note that since you updated to a npm mono repo sometime last night, you should update the README for import:

```
import { Card } from "@99xt/first-born";
```

Looks great so far btw.  Nice work.

**Comment by samsam-026** [comment] 2019-04-02 13:13
> ```
> import { Card } from "@99xt/first-born";
> ```

Thanks for the tip. 

The issue is now fixed in the new patch.

**Closed as completed by samsam-026** 2019-04-02 13:13 UTC
Labels: bug
